from time import sleep

def loadbar(iteration, total, prefix='', suffix ='',  decimals=1, length=100, fill='>'):
	percent = ('{0:.' + str(decimals) + 'f}').format(100 * (iteration/float(total)))
	filledLength = int(length * iteration // total)
	bar = fill * filledLength + '-' * (length - filledLength)
	print(f'\r{prefix} |{bar}| {percent}% {suffix}', end='\r')
	if iteration == total:
		print()

items = list(range(0, 50))
l = len(items)
loadbar(0, l, prefix='Progress:', suffix='Complete', length=l)
for i, item in enumerate(items):
	sleep(0.1)
	loadbar(i + 1, l, prefix='Progress:', suffix='Complete', length=l)
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
from random import *
import time as t
print('\033[1;32m' + """
        ========       //\\         []========[] []          
        []            //  \\        []        [] []        
        []           //    \\       []        [] []
        []          //      \\      []========[] []
        []         // =======\\     []    \\      []
        []        //          \\    []     \\     []
        []       //            \\   []      \\    []
        ========//              \\  []       \\   ==========
""")

print('\033[1;34m' + """     
   ================================================= 
   |           Peso Wifi Voucher Generator         |
   |                                               |
   |             Coded by: Carl Hackz              |
   |                                               |
   =================================================
   """)  
print('\033[1;31m' + """                    
""") 
print("Note This Is Made For Eduacational Purpose Only")
import time as t  
import random
t.sleep(5)
upper_case = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
numbers = "1234567890"
Use_for = upper_case + numbers
length_for_pass = 5
print("Generating Voucher Codes:")

password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)

password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)
password ="".join(random.sample(Use_for,length_for_pass))
print("",password)
t.sleep(0.1)